stats:
    image: nhong/influxcollector:dockerstats
    links:
        - influx
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        INFLUXDB_URL: http://root:root@influx:8086/test
        DEBUG: docker-stats

influx:
    image: influxdb
    ports:
        - 8083:8083
        - 8086:8086
    volumes:
        - ~/.influxdb:/var/lib/influxdb

grafana:
    image: grafana/grafana
    links:
        - influx
    ports:
        - 3000:3000
